### ISSUE TITLE
Usage details

### ISSUE THREAD

**Issue by wr47h** [JuxhinDB/synner#1]
Not exactly an issue, but how to do what you have mentioned in the 1st line of README?
`If you want to get this to work, you need to configure the Ethernet dst and src to point to your interface's MAC address and the target interface MAC address.`

**Comment by JuxhinDB** [comment]
Hey @wr47h -- Great question. The README is currently just in a placeholder state right now. I'll be working on refining it along the lines of my other [project](https://github.com/JuxhinDB/gw2-api-interface), so I apologise for that. 

To answer your question, if you take a look at the code here:

https://github.com/JuxhinDB/synner/blob/84797a033db5f6d12f7e4c9a4f005aca7214d799/src/main.rs#L56-L62

You will notice that the Ethernet header has its source and destination MAC addresses hardcoded. I should instead pull these details from the network interface however for the time being you would need to do it yourself. The source MAC address is simply your local NIC card which can be pulled like so:

```
$ ipconfig /all

Ethernet adapter vEthernet (DockerNAT):

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter #3
   Physical Address. . . . . . . . . : 00-15-5D-00-02-1E  <-- This guy here
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   IPv4 Address. . . . . . . . . . . : 10.0.75.1(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :
   DNS Servers . . . . . . . . . . . : fec0:0:0:ffff::1%1
                                       fec0:0:0:ffff::2%1
                                       fec0:0:0:ffff::3%1
   NetBIOS over Tcpip. . . . . . . . : Disabled
```

Whereas the Target MAC address would depend on the following:

1. If it's a local target (e.g. VM or machine on your network) then you need to find the MAC address of its [generally Ethernet] interface (e.g. `eth0` for Linux). 

2. If it's a remote target (e.g. Test DigitalOcean Droplet) then you would need to pass the MAC address of your default gateway (which is your router). If you know the router's IP you can find this by running `arp -d {router_ip}`

When that is done, you can run `cargo build` then `cargo run {target_ip} {network_interface_name}` for example:

`cargo run 192.168.33.10 \DEVICE\NNN_{FOO}`

If you don't know your network interface beforehand, you can run the command once with a dummy value like I did above, and see what the console prints out thanks to:

https://github.com/JuxhinDB/synner/blob/84797a033db5f6d12f7e4c9a4f005aca7214d799/src/main.rs#L106

OR you can use tools like WireShark in order to see what interfaces it can pull.

---

###### Caveats

1. If you want to run this on Windows like I did, you're going to go through some growing pains. Libpnet (which is was builds and sends the packets) requires WinPcap in order to work. I recommend checking out their [documentation](https://github.com/libpnet/libpnet#windows)

2. **Important**: You need to make sure your terminal/command prompt is running with admin privileges in order to be able to pull the list of network interfaces. 

I hope this helps.

**Comment by JuxhinDB** [comment]
This should now be resolved as of:

https://github.com/JuxhinDB/synner/commit/76b41cef70a9374dc99b45d0a357cd4ebf80a707 and https://github.com/JuxhinDB/synner/commit/ece96553ca1a11912b74ca7a872adc00c1e737a7

---

You should be able to simply send a SYN packet by running:

`$ cargo run 1.1.1.1 eth0`

I'll be implement packet count to adjust how many packets to send and will polish the README. Closing issue; if you have any further questions feel free to re-open. :-)

**Comment by wr47h** [comment]
Right, now I understand. Thank you for the explanation. :smiley:
